version: '3'

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
  config_server:
    build: './configServer'
  discovery_server:
    build: './discoveryServer'
  gateway_server:
    build: './gatewayServer'
  rest_client_server:
    build: './restClientServer'
  user_server:
    build: './userServer'