server:
  port: 8085

spring:
  application:
    name: userServer

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service.eastus.azurecontainer.io:8761/eureka # TODO